### ISSUE TITLE
K40-Whisperer doesn't start

### ISSUE THREAD

**Issue by maganzi** [rsre/K40-Whisperer-macOS#3]
Hi,
I have the following error message:

`OPEN Python k40_whisperer.py
Password:
Unable to load USB library (Sending data to Laser will not work.)
Traceback (most recent call last):
  File "k40_whisperer.py", line 28, in <module>
    from svg_reader import SVG_READER
  File "/Applications/K40_Whisperer-0.34_src/svg_reader.py", line 28, in <module>
    import inkex
  File "/Applications/K40_Whisperer-0.34_src/inkex.py", line 35, in <module>
    from   lxml import etree
ImportError: No module named lxml
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.`

what´s wrong?

**Comment by rsre** [comment]
Have you installed the dependencies with homebrew?

You can do so following the steps in README.md

**Comment by maganzi** [comment]
Yes i have installed all dependencies like in the README.md is described.

**Comment by rsre** [comment]
What version of macOS are you running?

**Comment by maganzi** [comment]
Mojave

**Comment by maganzi** [comment]
MacBook Air 13“ 2019

**Comment by maganzi** [comment]
10.14.6 (18G87)

**Comment by rsre** [comment]
It's the same version I'm running.

If you are sure you have installed the dependencies the only other thing I can think of is to try to rebuild from source or install [stephenhouser](https://github.com/stephenhouser/k40-whisperer) version.
